"""Migration script template

Add current_tick to SimulationRun

Revision ID: 314b2ef6635b
Revises: 002_agent_integration
Create Date: 2026-01-15 16:36:32.629817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '314b2ef6635b'
down_revision = '002_agent_integration'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_market_state_run'), table_name='market_state')
    op.drop_index(op.f('idx_market_state_tick'), table_name='market_state')
    op.drop_table('market_state')
    op.drop_index(op.f('idx_agent_decisions_role'), table_name='agent_decisions')
    op.drop_index(op.f('idx_agent_decisions_run'), table_name='agent_decisions')
    op.drop_index(op.f('idx_agent_decisions_tick'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_index(op.f('idx_event_responses_agent'), table_name='event_responses')
    op.drop_index(op.f('idx_event_responses_event'), table_name='event_responses')
    op.drop_index(op.f('idx_event_responses_run'), table_name='event_responses')
    op.drop_index(op.f('idx_event_responses_tick'), table_name='event_responses')
    op.drop_table('event_responses')
    op.add_column('simulation_runs', sa.Column('current_tick', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_runs', 'current_tick')
    op.create_table('event_responses',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tick', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('agent_response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actions_taken', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], name=op.f('event_responses_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('event_responses_pkey'))
    )
    op.create_index(op.f('idx_event_responses_tick'), 'event_responses', ['run_id', 'tick'], unique=False)
    op.create_index(op.f('idx_event_responses_run'), 'event_responses', ['run_id'], unique=False)
    op.create_index(op.f('idx_event_responses_event'), 'event_responses', ['event_id'], unique=False)
    op.create_index(op.f('idx_event_responses_agent'), 'event_responses', ['agent_role'], unique=False)
    op.create_table('agent_decisions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tick', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('observations', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('reasoning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proposed_actions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('executed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], name=op.f('agent_decisions_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_decisions_pkey'))
    )
    op.create_index(op.f('idx_agent_decisions_tick'), 'agent_decisions', ['run_id', 'tick'], unique=False)
    op.create_index(op.f('idx_agent_decisions_run'), 'agent_decisions', ['run_id'], unique=False)
    op.create_index(op.f('idx_agent_decisions_role'), 'agent_decisions', ['agent_role'], unique=False)
    op.create_table('market_state',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tick', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('awareness_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trust_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('viral_coefficient', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('market_dynamics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('price_perception', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quality_perception', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('brand_strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], name=op.f('market_state_run_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('market_state_pkey'))
    )
    op.create_index(op.f('idx_market_state_tick'), 'market_state', ['run_id', 'tick'], unique=False)
    op.create_index(op.f('idx_market_state_run'), 'market_state', ['run_id'], unique=False)
    # ### end Alembic commands ###
